config/routes.rb
Politicos::Application.routes.draw do
  root :to => "home#index"
  resources :distritos


  match "/update_distritos" => "home#update_distritos"
   match "/update_circunscripciones" => "home#update_circunscripciones"

   match '/diputados' => 'home#diputados', :as => :diputados
   match '/senadores' => 'home#senadores', :as => :senadores
   match '/home/searchsenadores' => 'home#searchsenadores', :as => :searchsenadores
   match '/home/searchdiputados' => 'home#searchdiputados', :as => :searchdiputados
   match '/home/search' => 'home#search', :as => :search
   match '/home/layers' => 'home#layers', :as => :layers
    match '/home/searchlayers' => 'home#searchlayers', :as => :searchlayers

match '/home/layersdistritos' => 'home#layersdistritos', :as => :layersdistritos
match '/home/layerscircunscripciones' => 'home#layerscircunscripciones', :as => :layerscircunscripciones


end

app/views/layouts/_lateral.html.erb
 <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <% if(@render_senadores) %>
                <%= form_tag(:controller => "home", :action => "searchsenadores", :method => "post")%>
             <% end %>

               <% if (@render_diputados)%>
               <%=  form_tag(:controller => "home", :action => "searchdiputados", :method => "post")%>
             <% end %>

              <% if(@render_todos)%>
                <%=   form_tag(:controller => "home", :action => "search", :method => "post")%>

              <%end%>

               <% if(@render_distritos || @render_circunscripcion)%>
                <%=   form_tag(:controller => "home", :action => "searchlayers", :method => "post")%>

              <%end%>

              
             <div class="control-group">
               
                <div class="controls">

                     <% if(@render_diputados) %>
                     <li class="nav-header">Región</li> 
                <%= select_tag "region_id", options_from_collection_for_select(@regiones, "id", "nombre", {:class => 'dropdown-toggle'}), :prompt => "Seleccione Region", :onchange => "update_distritos_div(this.value)" %>
              
               <%end %>

                 <% if(@render_senadores) %>
                 <li class="nav-header">Región</li> 
                <%= select_tag "region_id", options_from_collection_for_select(@regiones, "id", "nombre", {:class => 'dropdown-toggle'}), :prompt => "Seleccione Region", :onchange => "update_circunscripcion_div(this.value)" %>
              
               <%end %>

              <% if(@render_todos) %>
              <li class="nav-header">Región</li> 
                <%= select_tag "region_id", options_from_collection_for_select(@regiones, "id", "nombre", {:class => 'dropdown-toggle'}), :prompt => "Seleccione Region" %>
              
               <%end %>



                </div>


         
            <% if(@render_diputados) %>
              <li class="nav-header">Distrito</li>
              <div class="controls">

              <div id="distritosDiv">
                  <%= render :partial => 'home/distritos', :object => @distritos %>
              </div>
              </div>

               <%end %>


               <% if(@render_distritos) %>
              <li class="nav-header">Distrito</li>
              <div class="controls">

              <div id="distritosDiv">
                  <%= render :partial => 'home/distritos', :object => @distritos %>
              </div>
              </div>

               <%end %>

              <% if(@render_senadores) %>

               <li class="nav-header">Circunscripción</li>
            <div class="controls">

              <div id="circunscripcionDiv">
                  <%= render :partial => 'home/circunscripciones', :object => @circunscripciones %>
              </div>
            </div>
              <%end %>


               <% if(@render_circunscripcion) %>

               <li class="nav-header">Circunscripción</li>
            <div class="controls">

              <div id="circunscripcionDiv">
                  <%= render :partial => 'home/circunscripciones', :object => @circunscripciones %>
              </div>
            </div>
              <%end %>

              <% if(@render_todos || @render_senadores || @render_diputados) %>

              <li class="nav-header">Año</li>
              <div class="controls">
                <%= select_year(Date.today, :start_year => 1990, :end_year => 2012) %>
              </div>

              
             <%end %>
            

              <div class="controls">
         
              <%= submit_tag "Buscar", :class => "btn btn-primary" %>
             </div>
              </ul>
              </div>
          </div><!--/.well -->


<script>

          
function update_distritos_div(region_id) {  
  jQuery.ajax({
    url: "/update_distritos",
    type: "GET",
    data: {"region_id" : region_id},
    dataType: "html",
    success: function(data) {
      jQuery("#distritosDiv").html(data);
    }
  });
}

function update_circunscripcion_div(region_id) {  
  jQuery.ajax({
    url: "/update_circunscripciones",
    type: "GET",
    data: {"region_id" : region_id},
    dataType: "html",
    success: function(data) {
      jQuery("#circunscripcionDiv").html(data);
    }
  });
}



</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Politicos", root_path, :class => 'brand' %>

<ul class="nav">
<li><%= link_to "Senadores", senadores_path  %></li>
<li><%= link_to "Diputados", diputados_path  %></li>
<li><%= link_to "Distritos", layersdistritos_path  %></li>
<li><%= link_to "Circunscripciones", layerscircunscripciones_path  %></li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Politicos" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Politicos" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>






    <div id="main" role="main">
      <div class="container-fuid">
        
           <div class="row-fuid">

             <div class="span3">


         <%= render 'layouts/lateral' %>



        </div><!--/span-->

            <div class="span9">
              <%= render 'layouts/messages' %>


              <%= yield %>
            </div>
          </div>
          <footer>
    <%= yield :scripts %>
      </footer>
        </div>

    </div> <!--! end of #main -->


  </body>
</html>